### ISSUE TITLE
textAlignment属性无效

### ISSUE THREAD

**Issue by longitachi** [shevakuilin/SKAutoScrollLabel#1]
代码中写死了center居中

**Comment by shevakuilin** [comment]
当初这么写是因为居中效果最好，你是有实际需求需要改变textAlignment的显示位置吗

**Comment by longitachi** [comment]
我想着既然公布出来api，就应该可以满足自定义的需求，可以默认居中，我已经改过了。

**Comment by shevakuilin** [comment]
嗯，确实当初没有考虑到这一点需求，因为一般来说，需求都是方向上的控制，文本上确实忽略了，抱歉
