### ISSUE TITLE
从前台切到后台，再从后台切到前台的问题。

### ISSUE THREAD

**Issue by Zy-developer** [shevakuilin/SKAutoScrollLabel#2]
从前台切到后台，再从后台切到前台，文字就不动了。能修复吗？

**Comment by shevakuilin** [comment]
是希望滚动状态在前后台切换中保持连贯吗

2018-04-26 16:55 GMT+08:00 Zy <notifications@github.com>:

**Comment by Zy-developer** [comment]
不是，是我把App从前台切换到后台，然后切换回前台，文字就停在那边，完全不滚动了。

**Comment by shevakuilin** [comment]
该库已进行重构，反馈问题均已解决，并优化了滚动流畅度
