### ISSUE TITLE
NSRunLoopCommonModes

### ISSUE THREAD

**Issue by leslie0320** [shevakuilin/SKAutoScrollLabel#4]
- (void)creatDisplayLink {
    self.displayLinke = [CADisplayLink displayLinkWithTarget:self selector:@selector(processDisplayLink)];
    [self.displayLinke addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
}

**Comment by leslie0320** [comment]
这样写,进行UI交互时,label也在滚动

**Comment by shevakuilin** [comment]
感谢反馈
