### ISSUE TITLE
textcontent无法设置新内容，presentvc后无法滚动

### ISSUE THREAD

**Issue by Roen-Ro** [shevakuilin/SKAutoScrollLabel#6]
有两个问题，希望可以更新解决
1.textContent初始化了以后，再次设置不生效，无法替换掉之前设置的内容
2.在执行了presentViewController...之后，不会滚动了，调用continueScroll也不行

**Comment by shevakuilin** [comment]
会尽快解决

Roen <notifications@github.com>于2019年8月6日 周二09:16写道：

**Comment by shevakuilin** [comment]
已修复，稍后请更新至 0.0.5

**Comment by Roen-Ro** [comment]
谢谢！
