### ISSUE TITLE
两个优化建议

### ISSUE THREAD

**Issue by Roen-Ro** [shevakuilin/SKAutoScrollLabel#7]
首先感谢你的贡献

还有两个优化建议
1、当字符展示长度小于label的frame width的时候，不需要滚动显示。
2、提供reset功能，当pausescroll的时候，我希望文本按照设定的textAlignment来显示

**Comment by shevakuilin** [comment]
感谢你的建议，我会在最近完善相应的功能，不过由于工作原因精力有限，也欢迎你提出PR，一起参与SKAutoScrollLabel的维护

**Comment by Roen-Ro** [comment]
你已经做得很好了，期待你的完善， take your time.
