### ISSUE TITLE
文字过少的时候，会闪一下在出现，不会在尾部跟随，

### ISSUE THREAD

**Issue by tanghk** [shevakuilin/SKAutoScrollLabel#8]

**Comment by shevakuilin** [comment]
能提供具体的 case 吗

**Comment by tanghk** [comment]
self.scrollLabel = [[SKAutoScrollLabel alloc] initWithTextContent:@"你指尖跃动的电光, 是我此生不灭的信仰 " direction:self.scrollType];
将demo中 TextContent的文字变少。 在6p上运行就可以看到

**Comment by shevakuilin** [comment]
我会找时间会尽快修复

**Comment by shevakuilin** [comment]
已修复，请更新至0.0.6
