### ISSUE TITLE
在 tableview 上使用有些问题

### ISSUE THREAD

**Issue by kayaYuan** [shevakuilin/SKAutoScrollLabel#9]
我在tableviewCell上使用这个控件，因为每一个cell中的内容都不一样，滑动之后就有错乱了

**Comment by shevakuilin** [comment]
可以提供具体的使用 case 吗？

**Comment by kayaYuan** [comment]
现在用了一个讨巧的办法是在tableview 的 cellforRowIndexPath 添加 跑马灯，然后在endDisplayCell 移除，这样就正常了


									Kayakaya
在 2019年9月27日 +0800 09:39，ShevaKuilin <notifications@github.com>，写道：

**Comment by shevakuilin** [comment]
抱歉之前比较忙，我最近会找时间修复这个问题，还是希望能够提供一下出问题的代码段，来帮助复现这一问题

**Comment by kayaYuan** [comment]
没事，也不算是问题，我写了个demo测试，不过demo已经删除了，你也可以自己写一下，就是将tableview cell上添加跑马灯，跑马灯的内容是cell的index row，滚动之后就会错乱了，是cell复用导致的


									Kayakaya
在 2019年10月9日 +0800 11:46，ShevaKuilin <notifications@github.com>，写道：
